Suppress warnings + fix errors
Warning: android-sdk: No available formula with the name "android-platform-tools"
'conflicts_with "android-platform-tools"' should be removed from android-sdk.rb.
Please report this to the mrbfrank/android-sdk-24 tap!

Error: Calling <<-EOS.undent is disabled!
Use <<~EOS instead.
/usr/local/Homebrew/Library/Taps/mrbfrank/homebrew-android-sdk-24/android-sdk.rb:46:in `block in install'
Please report this to the mrbfrank/android-sdk-24 tap!
Or, even better, submit a PR to fix it!